import { Quiz } from '../models/Quiz.js';
import { Question } from '../models/Question.js';
import { aiClient } from '../services/aiClient.js';

function normalizeOptions(type, options, correctAnswer) {
  if (type !== 'multiple_choice' || !Array.isArray(options)) return options;
  const hasCorrect = options.some((o) => o.isCorrect);
  if (hasCorrect || !correctAnswer) return options;
  return options.map((o) => ({ ...o, isCorrect: o.id === correctAnswer }));
}

export async function generateQuiz(req, res, next) {
  try {
    const { topic, difficulty, questionCount, types } = req.body;
    const result = await aiClient.generateQuiz({
      topic,
      difficulty: difficulty || 3,
      questionCount: questionCount || 5,
      types: types || ['multiple_choice', 'true_false'],
    });

    const quiz = await Quiz.create({
      teacherId: req.user._id,
      title: `AI: ${topic}`,
      topic,
      difficulty: difficulty || 3,
      description: 'Generated by AI — review before publishing',
      isPublished: false,
      questionCount: result.questions?.length || 0,
    });

    const questions = [];
    for (let i = 0; i < (result.questions || []).length; i++) {
      const q = result.questions[i];
      const question = await Question.create({
        quizId: quiz._id,
        order: i,
        type: q.type || 'multiple_choice',
        text: q.text,
        options: normalizeOptions(q.type || 'multiple_choice', q.options, q.correctAnswer),
        correctAnswer: q.correctAnswer,
        explanation: q.explanation,
        difficulty: q.difficulty || difficulty,
        points: 10,
      });
      questions.push(question);
    }

    await Quiz.findByIdAndUpdate(quiz._id, { questionCount: questions.length });
    res.status(201).json({ quiz, questions });
  } catch (err) {
    next(err);
  }
}

export async function liveAssistant(req, res, next) {
  try {
    const result = await aiClient.liveAssistant(req.body);
    res.json(result);
  } catch (err) {
    next(err);
  }
}

export async function chat(req, res, next) {
  try {
    const result = await aiClient.chat(req.body);
    res.json(result);
  } catch (err) {
    next(err);
  }
}

export async function revisionPlan(req, res, next) {
  try {
    const result = await aiClient.revisionPlan({
      ...req.body,
      topicsProgress: req.user.topicsProgress,
    });
    res.json(result);
  } catch (err) {
    next(err);
  }
}

export async function explainAnswer(req, res, next) {
  try {
    const result = await aiClient.explainAnswer(req.body);
    res.json(result);
  } catch (err) {
    next(err);
  }
}
